# Generated by Django 5.1.7 on 2025-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
