# Generated by Django 5.1.7 on 2025-04-02 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_completed_todo_is_done_remove_todo_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
